name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: 8.0.332+9
          cache: 'maven'
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Update README
      if: always()
      run: |
        echo "Build status: ${{ job.status }}" >> ${{ github.workspace }}/README.md
    #- name: Commit and push changes
    #  if: always()
    #  run: |
    #    git config --global user.email "caterina.vallotto@studenti.unipd.it"
    #    git config --global user.name "cvallott"
    #    git add README.md
    #    git commit -m "Update README with build status"
    #    git push


